### ISSUE TITLE
smartthinq crashing Hass.io after update 0.89.2

### ISSUE THREAD

**Issue by ctih** [sampsyo/hass-smartthinq#10]
Anyone else?

Log Details (ERROR)
Mon Mar 18 2019 14:24:01 GMT+0100 (Centraleuropæisk normaltid)
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 68, in ban_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 98, in auth_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 112, in handle
    result = await result
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/config/core.py", line 21, in post
    errors = await async_check_ha_config_file(request.app['hass'])
  File "/usr/local/lib/python3.7/site-packages/homeassistant/config.py", line 779, in async_check_ha_config_file
    check_ha_config_file, hass)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/scripts/check_config.py", line 371, in check_ha_config_file
    platform = loader.get_platform(hass, domain, p_name)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 97, in get_platform
    base_paths)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/smartthinq/climate.py", line 17, in <module>
    'HEAT': climate.STATE_HEAT,
AttributeError: module 'homeassistant.components.climate' has no attribute 'STATE_HEAT'

**Comment by adrianrdzv** [comment]
Same here, although STATE_HEAT is still there:

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/climate/const.py#L39

**Comment by adrianrdzv** [comment]
Fixed by #11
