### ISSUE TITLE
AttributeError: module 'homeassistant.components.climate' has no attribute 'ClimateDevice

### ISSUE THREAD

**Issue by thepuncake** [sampsyo/hass-smartthinq#107]
This started happening after updating home assistant last night, not sure what's causing it. Ac was working flawlessly before that, anybody ran into this as well?

`Logger: homeassistant.loader
Source: custom_components/smartthinq/climate.py:93
Integration: hass-smartthinq (documentation, issues)
First occurred: 4:15:51 PM (1 occurrences)
Last logged: 4:15:51 PM

Unexpected exception importing platform custom_components.smartthinq.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 583, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/smartthinq/climate.py", line 93, in <module>
    class LGDevice(climate.ClimateDevice):
AttributeError: module 'homeassistant.components.climate' has no attribute 'ClimateDevice'
`

**Comment by thepuncake** [comment]
Ok not sure why but I had ClimateDevice instead of ClimateEntity. It works now but I'm boggled as to why. I think I had to change it at some point when it broke before and that fixed it?
