### ISSUE TITLE
HVAC stopped to work recently

### ISSUE THREAD

**Issue by GregoryOrciuch** [sampsyo/hass-smartthinq#109]
HVAC stopped to work recently :/ 

Is this project still alive ?

```
2022-05-11 18:36:18 ERROR (MainThread) [homeassistant.setup] Error during setup of component smartthinq
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq/__init__.py", line 69, in setup
    client = wideq.Client.from_token(refresh_token, region, language)
  File "/usr/local/lib/python3.9/site-packages/wideq/client.py", line 210, in from_token
    client.refresh()
  File "/usr/local/lib/python3.9/site-packages/wideq/client.py", line 193, in refresh
    self._session, self._devices = self.auth.start_session()
  File "/usr/local/lib/python3.9/site-packages/wideq/core.py", line 361, in start_session
    session_info = login(self.gateway.api_root, self.access_token,
  File "/usr/local/lib/python3.9/site-packages/wideq/core.py", line 258, in login
    return lgedm_post(url, data)
  File "/usr/local/lib/python3.9/site-packages/wideq/core.py", line 213, in lgedm_post
    raise APIError(code, message)
wideq.core.APIError: ('0110', '약관동의 미동의 상태입니다.')

```

**Comment by GregoryOrciuch** [comment]
if anybody steps into same problem, the Korean message says it's due to missing the Term&Condition re-agreement.
You need now to go thru token issue process using WideQ program, the reconfigure hass with new refresh token.

**Comment by sampsyo** [comment]
Thanks!! I added a special error handler for this error code, so messages might be marginally more helpful for users who encounter this problem in the future.
