### ISSUE TITLE
Does not work after update.

### ISSUE THREAD

**Issue by skazo4nik** [sampsyo/hass-smartthinq#82]
After update integration does not work =(
Here is log:

smartthinq: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 335, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_device_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq/climate.py", line 344, in update
    self.check_power()
  File "/config/custom_components/smartthinq/climate.py", line 313, in check_power
    power = self._ac.get_power()
  File "/usr/local/lib/python3.8/site-packages/wideq/ac.py", line 324, in get_power
    value = self._get_config('InOutInstantPower')
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 431, in _get_config
    data = self.client.session.get_device_config(
  File "/usr/local/lib/python3.8/site-packages/wideq/core.py", line 486, in get_device_config
    res = self.post('rti/rtiControl', {
  File "/usr/local/lib/python3.8/site-packages/wideq/core.py", line 394, in post
    return lgedm_post(url, data, self.auth.access_token, self.session_id)
  File "/usr/local/lib/python3.8/site-packages/wideq/core.py", line 213, in lgedm_post
    raise APIError(code, message)
wideq.core.APIError: ('0111', '제품 응답 지연')

**Comment by aleksandryants** [comment]
Same thing with me

**Comment by mew0717** [comment]
same issue here

**Comment by AvirupDas** [comment]
Same issue for me

**Comment by vk2him** [comment]
Mine broke as well when I updated - damn!

**Comment by vk2him** [comment]
After update, mine broke - I had to get a new token via the $ python3 example.py -c US -l en-US process and it then worked again ....
