### ISSUE TITLE
I can't configure

### ISSUE THREAD

**Issue by spp12345** [sampsyo/hass-smartthinq#85]
configures according to the instructions. I added the token to the file configuration.yaml. PL region, language pl-PL. Do they know what I'm doing wrong?

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq/__init__.py", line 69, in setup
    client = wideq.Client.from_token(refresh_token, region, language)
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 210, in from_token
    client.refresh()
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 192, in refresh
    self._auth = self.auth.refresh()
  File "/usr/local/lib/python3.8/site-packages/wideq/core.py", line 370, in refresh
    new_access_token = refresh_auth(self.gateway.oauth_root,
  File "/usr/local/lib/python3.8/site-packages/wideq/core.py", line 299, in refresh_auth
    raise TokenError()
wideq.core.TokenError`

**Comment by RaulLimaPT** [comment]
It's incredible how often this message comes up in so many different scenarios, and I never found a straight answer about what it is causing it, or what it means. Home Assistant could improve these error messages, because the way it is, it is pointless (it is just like saying "An error occurred.").
And the community seems not been able to understand what that even means, by shooting guesses, since no one has a proper explanation.
I've been trying to fix this bloody issue for weeks, and I am about to give up on HA. Typical in open-source software.
Don't get me wrong, I support these type of projects, but it's a pain in the b*** when something is erroring and no documentation exists to troubeshoot.
