### ISSUE TITLE
Anyone else not able to get integration to work starting today?

### ISSUE THREAD

**Issue by monsieurlatte** [sampsyo/hass-smartthinq#96]
2021-03-04 15:44:25 ERROR (MainThread) [homeassistant.setup] Error during setup of component smartthinq
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/smartthinq/__init__.py", line 69, in setup
client = wideq.Client.from_token(refresh_token, region, language)
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 209, in from_token
client._auth = core.Auth(client.gateway, None, refresh_token)
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 103, in gateway
self._gateway = core.Gateway.discover(
File "/usr/local/lib/python3.8/site-packages/wideq/core.py", line 318, in discover
gw = lgedm_post(GATEWAY_URL,
File "/usr/local/lib/python3.8/site-packages/wideq/core.py", line 203, in lgedm_post
out = res.json()[DATA_ROOT]
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kannan-balasubramanian** [comment]
I was able to set it up today and 1 of two ACs is showing up.
My HACS version is 1.9.0.
